# Generated by Django 4.0.3 on 2023-03-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_user_model_category_alter_user_model_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatemodel',
            old_name='User_Id',
            new_name='User_email',
        ),
    ]
