# Generated by Django 4.0.3 on 2023-03-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_rename_user_id_candidatemodel_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatemodel',
            old_name='User_email',
            new_name='User_Id',
        ),
    ]
