# Generated by Django 4.0.3 on 2023-03-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_rename_user_id_candidatemodel_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemodel',
            name='Resume',
            field=models.FileField(upload_to='media/'),
        ),
    ]
