# Generated by Django 4.0.3 on 2023-03-11 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_alter_candidatemodel_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Sector', models.CharField(max_length=100)),
                ('Company_Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Company_link', models.URLField()),
                ('Recruiter_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
