# Generated by Django 4.0.3 on 2023-03-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_recruitermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Type', models.CharField(max_length=100)),
                ('Job_Sector', models.CharField(max_length=1000)),
                ('Job_Description', models.TextField()),
                ('Job_Salary_Offer', models.IntegerField()),
                ('Recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.recruitermodel')),
            ],
        ),
    ]
