# Generated by Django 4.0.3 on 2023-03-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_recruitment_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_model',
            name='Gender',
        ),
    ]
